name: Deploy Frontend to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd /home/stampia-prod
            echo "📥 Descargando últimos cambios..."
            git pull origin main

            echo "📥 Descargando últimos cambios de las interfaces"
            git submodule update --init --recursive
            cd shared
            git pull origin main
            cd ..

            echo "📦 Instalando dependencias..."
            npm install

            echo "🏗️ Ejecutando build del frontend..."
            NEXT_PUBLIC_API_URL=https://api.stampia.app \
            NEXT_PUBLIC_APP_NAME="Stampia" \
            NEXT_PUBLIC_ENVIRONMENT=production \
            FRONTEND_URL=https://stampia.app \
            npm run build

            echo "🔄 Reiniciando aplicación con PM2..."
            pm2 restart stampia-prod || pm2 start ecosystem.config.js --only stampia-prod

            echo "✅ Despliegue completado exitosamente!"

      - name: Health Check
        run: |
          sleep 30
          curl -f https://stampia.app || exit 1
          echo "✅ Frontend funcionando correctamente"

      - name: Notify Success
        if: success()
        run: |
          echo "🚀 Frontend deployment to production successful!"
          echo "URL: https://stampia.app"
          echo "Environment: Production"
