name: Deploy Frontend to Development

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          NEXT_PUBLIC_API_URL=https://api-dev.stampia.luciano-yomayel.com \
          NEXT_PUBLIC_APP_NAME="Stampia Dev" \
          NEXT_PUBLIC_ENVIRONMENT=development \
          npm run build

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            cd /home/stampia-dev
            echo "📥 Descargando últimos cambios..."
            git pull origin dev

            echo "📦 Instalando dependencias..."
            npm install

            echo "🏗️ Ejecutando build del frontend..."
            NEXT_PUBLIC_API_URL=https://api-dev.stampia.luciano-yomayel.com \
            NEXT_PUBLIC_APP_NAME="Stampia Dev" \
            NEXT_PUBLIC_ENVIRONMENT=development \
            npm run build

            echo "🔄 Reiniciando aplicación con PM2..."
            pm2 restart stampia-dev || pm2 start ecosystem.config.js --only stampia-dev

            echo "✅ Despliegue completado exitosamente!"

      - name: Health Check
        run: |
          sleep 30
          curl -f https://dev.stampia.luciano-yomayel.com || exit 1
          echo "✅ Frontend funcionando correctamente"
